"""Literature-grounded paradigm library for psychopy-mcp.

Each paradigm lives in its own module exposing:
  SPEC          : dict — canonical design, FIXED surface params, timing, refs
  build_trials  : (**opts) -> list[trial]  (engine-ready trials; see engine.py)

The model invokes these through three MCP tools (list_paradigms / get_paradigm /
scaffold_paradigm). Because every paradigm runs through the shared engine and
pulls surface parameters from its SPEC, generated experiments match the
published methodology and keep font size / position constant across conditions.
"""
from __future__ import annotations

import importlib
from pathlib import Path

# key -> module name (one module per paradigm)
REGISTRY = [
    "stroop", "flanker", "simon", "gonogo", "posner", "stopsignal", "ant",
    "nback", "sternberg", "visualsearch", "taskswitch", "lexdecision",
    "mentalrotation", "dotprobe", "deception",
]

from psychopy_mcp.paths import CUSTOM_DIR, PROJECT_ROOT  # noqa: E402

_PKG = __name__


def _mod(key: str):
    return importlib.import_module(f"{_PKG}.{key}")


def _custom_path(key: str) -> Path | None:
    p = CUSTOM_DIR / f"{key.lower()}.json"
    return p if p.exists() else None


def list_custom() -> list[str]:
    if not CUSTOM_DIR.exists():
        return []
    return sorted(p.stem for p in CUSTOM_DIR.glob("*.json"))


def list_paradigms() -> list[dict]:
    out = []
    for key in REGISTRY:
        try:
            spec = _mod(key).SPEC
            out.append({"key": key, "name": spec["name"],
                        "summary": spec["summary"], "builtin": True})
        except Exception as e:  # a broken module shouldn't hide the rest
            out.append({"key": key, "error": repr(e)})
    from . import custom as _custom
    for key in list_custom():
        try:
            spec = _custom.load(_custom_path(key))
            out.append({"key": key, "name": spec.get("name", key),
                        "summary": spec.get("summary", ""), "builtin": False})
        except Exception as e:
            out.append({"key": key, "error": repr(e)})
    return out


def get_paradigm(key: str) -> dict | None:
    key = key.lower()
    if key in REGISTRY:
        return _mod(key).SPEC
    p = _custom_path(key)
    if p:
        from . import custom as _custom
        return _custom.load(p)
    return None


def build_trials(key: str, **opts) -> list[dict]:
    key = key.lower()
    if key in REGISTRY:
        return _mod(key).build_trials(**opts)
    p = _custom_path(key)
    if p:
        from . import custom as _custom
        return _custom.build_trials(_custom.load(p), **opts)
    raise KeyError(key)


def generate_script(key: str, exp_name: str, opts: dict | None = None) -> str:
    """Emit a thin, runnable, editable experiment script for a paradigm."""
    key = key.lower()
    if key not in REGISTRY:
        if _custom_path(key):
            return _custom_script(key, exp_name, opts or {})
        raise KeyError(key)
    mod = _mod(key)
    # paradigms with control flow the generic engine can't express (e.g. an
    # adaptive staircase) ship their own standalone generator.
    if hasattr(mod, "generate"):
        return mod.generate(exp_name, opts or {}, PROJECT_ROOT)
    spec = mod.SPEC
    refs = "\n".join("  " + r for r in spec.get("references", []))
    opts = opts or {}
    return f'''"""{exp_name} — {spec["name"]} (literature-grounded).

Generated by psychopy-mcp from paradigm "{key}". Surface parameters (font size,
positions) and timing come from the paradigm spec, so all conditions match and
results stay comparable to:
{refs}

Edit OPTS to change trial counts etc.; the trial list and timing come from the
spec. Run via:  run_experiment("{exp_name}.py")
"""
import sys
sys.path.insert(0, r"{PROJECT_ROOT}")
from psychopy_mcp.paradigms import get_paradigm, build_trials
from psychopy_mcp.paradigms.engine import run

KEY = "{key}"
OPTS = {opts!r}

spec = get_paradigm(KEY)
trials = build_trials(KEY, **OPTS)
run(spec, trials, "{exp_name}")
'''


def _custom_script(key: str, exp_name: str, opts: dict) -> str:
    return f'''"""{exp_name} — custom paradigm "{key}" (generated by psychopy-mcp).

Loaded from custom_paradigms/{key}.json and run on the shared engine, so every
item shares the surface parameters declared in that file. Edit the JSON (or
OPTS) to change the design. Run via:  run_experiment("{exp_name}.py")
"""
import sys
sys.path.insert(0, r"{PROJECT_ROOT}")
from psychopy_mcp.paradigms import get_paradigm, build_trials
from psychopy_mcp.paradigms.engine import run

KEY = "{key}"
OPTS = {opts!r}

spec = get_paradigm(KEY)
trials = build_trials(KEY, **OPTS)
run(spec, trials, "{exp_name}")
'''
