"""Stop-signal task (Logan & Cowan 1984; Verbruggen et al. 2008/2019).

The adaptive SSD staircase and the need to capture responses that occur AFTER
the stop signal don't fit the generic phase engine, so this paradigm emits a
self-contained script with a proper non-blocking trial loop and a 1-up/1-down
staircase converging on p(respond|stop) = 0.5.
"""
from __future__ import annotations

SPEC = {
    "name": "Stop-Signal Task (SSRT)",
    "summary": ("Speeded two-choice go task; on 25% of trials a stop signal "
                "appears after a variable delay and the response must be "
                "cancelled. DV is SSRT, the latent stopping latency."),
    "references": [
        "Logan, G. D., & Cowan, W. B. (1984). On the ability to inhibit thought "
        "and action: A theory of an act of control. Psychological Review, "
        "91(3), 295-327.",
        "Verbruggen, F., et al. (2019). A consensus guide to capturing the "
        "ability to inhibit actions and impulsive behaviors in the stop-signal "
        "task. eLife, 8, e46323.",
    ],
    "conditions": ["go", "stop"],
    "condition_balance": "75% go / 25% stop",
    "task": "Respond LEFT/RIGHT to the arrow; if it turns RED, withhold.",
    "surface": {
        "units": "height", "background": "gray",
        "stim_pos": [0.0, 0.0], "stim_height": 0.12,
        "go_color": "white", "stop_color": "red",
        "fixation_char": "+", "fixation_height": 0.05,
    },
    "timing": {"fixation_sec": 0.25, "ssd_start_sec": 0.25, "ssd_step_sec": 0.05,
               "max_response_sec": 1.0, "iti_sec": 1.0},
    "responses": {"mapping": {"left": "f", "right": "j"}, "quit_key": "escape",
                  "note": "SSD adapts ±50 ms (1-up/1-down) from a 250 ms start."},
    "dv": ["SSRT (integration method recommended)", "p(respond|stop) ~ 0.5",
           "go RT, go error/omission rates"],
}


def build_trials(**opts):
    raise NotImplementedError(
        "stop-signal uses a standalone runner; use scaffold_paradigm('stopsignal', ...).")


def generate(exp_name: str, opts: dict, root) -> str:
    n_go = opts.get("n_go", 96)
    n_stop = opts.get("n_stop", 32)
    return f'''"""{exp_name} — Stop-Signal Task (SSRT), literature-grounded.

Generated by psychopy-mcp. Adaptive SSD staircase (start 250 ms, step 50 ms,
1-up/1-down). References:
  Logan & Cowan (1984), Psychological Review 91(3), 295-327.
  Verbruggen et al. (2019), eLife 8, e46323.

Edit N_GO / N_STOP below. Run via:  run_experiment("{exp_name}.py")
"""
import os
import random

from psychopy import visual, core, event, data, gui

N_GO, N_STOP = {n_go}, {n_stop}
SSD = 0.25            # starting stop-signal delay (s)
SSD_STEP = 0.05
MAX_RT = 1.0
FIX = 0.25
ITI = 1.0
KEYS = {{"left": "f", "right": "j"}}

info = {{"participant": "001", "session": "01"}}
if not gui.DlgFromDict(info, title="{exp_name}").OK:
    core.quit()
os.makedirs("data", exist_ok=True)
fname = os.path.join("data", f"{{info['participant']}}_{exp_name}_{{data.getDateStr()}}")

win = visual.Window(size=[1024, 768], color="gray", units="height", fullscr=False)
fix = visual.TextStim(win, text="+", height=0.05, color="white")
arrow = visual.TextStim(win, text="", height=0.12, bold=True)

trials = ["go"] * N_GO + ["stop"] * N_STOP
random.shuffle(trials)
exp = data.ExperimentHandler(name="{exp_name}", extraInfo=info, dataFileName=fname)
handler = data.TrialHandler(trials, nReps=1, method="sequential")
exp.addLoop(handler)

visual.TextStim(win, height=0.045, color="white", wrapWidth=1.5,
    text="Press F (left) or J (right) for the arrow direction.\\n"
         "If the arrow turns RED, try to STOP your response.\\n\\nSPACE to begin."
).draw()
win.flip(); event.waitKeys(keyList=["space"])

clock = core.Clock()
aborted = False
for trial in handler:
    direction = random.choice(["left", "right"])
    corr = KEYS[direction]
    glyph = "<" if direction == "left" else ">"
    fix.draw(); win.flip(); core.wait(FIX)

    arrow.text = glyph; arrow.color = "white"
    arrow.draw(); win.flip(); clock.reset()
    key, rt, stop_shown = None, None, False
    while clock.getTime() < MAX_RT:
        t = clock.getTime()
        if trial == "stop" and not stop_shown and t >= SSD:
            arrow.color = "red"; arrow.draw(); win.flip(); stop_shown = True
        pressed = event.getKeys(keyList=["f", "j", "escape"], timeStamped=clock)
        if pressed:
            k, rtv = pressed[0]
            if k == "escape":
                aborted = True; break
            key, rt = k, rtv; break
    if aborted:
        break

    if trial == "go":
        correct = int(key == corr)
        ssd_used = ""
    else:
        inhibited = key is None
        correct = int(inhibited)
        ssd_used = SSD
        SSD = min(MAX_RT, SSD + SSD_STEP) if inhibited else max(0.0, SSD - SSD_STEP)

    handler.addData("condition", trial)
    handler.addData("direction", direction)
    handler.addData("response", key)
    handler.addData("rt", rt)
    handler.addData("correct", correct)
    handler.addData("ssd", ssd_used)
    exp.nextEntry()
    win.flip(); core.wait(ITI)

exp.saveAsWideText(fname + ".csv")
print("SAVED:", fname + ".csv", flush=True)
win.close()
core.quit()
'''
